apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apis
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"

spec:
  rules:
    - http:
        paths:
          - path: /api/v1.0/ms1/
            pathType: Prefix
            backend:
              service:
                name: fiap-app-production-service
                port:
                  number: 8080
